databases:
  - name: parts31
    databaseName: parts31
    user: parts31

services:
  - type: web
    name: parts31
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: parts31
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false